---
- hosts: test
  user: root
  roles:
  - role: dochang.docker 
  vars:
  - files_dir: "{{ FILES_DIR|default('/tmp/curator/file') }}"
  tasks:
    - name: create config.yaml and rules directory
      file: path=/tmp/curator state=directory
      file: path=/tmp/curator/file state=touch
    - name: template for curator-service, timer
      template: src=templates/timer.conf.j2 dest=/etc/systemd/system/curator.timer owner=root group=root mode=0644
      template: src=templates/service.conf.j2 dest=/etc/systemd/system/curator.service owner=root group=root mode=0644
    - name: pull the image
      shell: docker pull nael4746/curator
    - name: Enable the service on boot
      shell: systemctl enable curator.timer
    - name: start the service
      shell: systemctl start curator.timer
